// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uigbjgmggffafrjkembn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZ2JqZ21nZ2ZmYWZyamtlbWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MTI3MTQsImV4cCI6MjA1NjM4ODcxNH0.ArVsCkqK-blOSLLS8aR504k0CgSwKzgpZYi3u4Ja0kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);